# version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - ./app/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - DB_URI=mongodb://mongo:27017/library-next-api
      - JWT_SECRET=codingwithabbas
      - JWT_EXPIRES=3d

  frontend:
    build: ./web
    container_name: frontend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  mongo-data: