apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: shaikbasit99/node-app:v1   # replace with your Docker Hub repo
        ports:
        - containerPort: 3000
        env:
        - name: DB_URI
          value: mongodb://mongo-service:27017/library-next-api
        - name: JWT_SECRET
          value: codingwithabbas
        - name: JWT_EXPIRES
          value: 3d
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 5000       # service port
      targetPort: 3000 # container port
  type: ClusterIP
