apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  clusterIP: None   # Headless service for StatefulSet
  selector:
    app: mongo
  ports:
    - port: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo-service
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest  # official image, no need to push
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:   # ✅ Replace PVC with emptyDir
      - name: mongo-data
        emptyDir: {}
  
