name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # needed for committing back to repo

    env:
      IMAGE_NAME: node-app
      REGISTRY: docker.io
      GIT_USER_NAME: shaikbasid123
      GIT_REPO_NAME: nodejs_application

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build & Push Docker Image
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ github.run_number }}
          docker build -t $REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG .
          docker push $REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 4. Update Kubernetes Deployment Manifest
      - name: Update k8s deployment with new image tag
        run: |
          sed -i "s/replaceImageTag/${IMAGE_TAG}/g" k8s/deployment.yaml

      # 5. Commit & Push updated manifest
      - name: Commit and push changes
        run: |
          git config user.email "shaikbasid50@gmail.com"
          git config user.name "${{ env.GIT_USER_NAME }}"
          git add k8s/deployment.yaml
          git commit -m "Update deployment image to version $IMAGE_TAG"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.GIT_USER_NAME }}/${{ env.GIT_REPO_NAME }} HEAD:main
